### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by titoBouzout** [phpfmt/sublime-phpfmt#225]
hi there, awesome package thank you, but a "minor" problem it does spam the console

phpfmt (php_ver) err:.......... 
phpfmt (php_ver) cmd:........

can you please wrap these prints into the "debug" flag, thanks!

**Comment by ccirello** [comment]
done

**Comment by ccirello** [comment]
Upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/9.23.1

**Comment by titoBouzout** [comment]
tyyyyyyyy

On 16 January 2016 at 18:43, Carlos Cirello <notifications@github.com>
wrote:

> Upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/9.23.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpfmt/sublime-phpfmt/issues/225#issuecomment-172260063>
> .
>



-- 
-- 
Tito

**Comment by titoBouzout** [comment]
this is not fixed, I just run into more blank prints. Maybe you could add a function print_debug and print_error, and check if there debug is enable and also if the thing to print is not empty.

**Comment by ccirello** [comment]
OK. Reopening the issue.

**Comment by ccirello** [comment]
@titoBouzout try this: https://github.com/phpfmt/sublime-phpfmt/commit/214ba9240dbb930e0e10818ea21b23928374cc86

**Comment by titoBouzout** [comment]
Thanks, a quick search for "print" in just the python file reveals there are still some non wrapped statements, example https://github.com/phpfmt/sublime-phpfmt/blob/master/phpfmt.py#L706-L716

idk, I think my suggestion was good. just create a function, then search of all "print" and send these to there.

**Comment by ccirello** [comment]
can you make a PR on it? I will merge it gladly

**Comment by titoBouzout** [comment]
https://github.com/phpfmt/sublime-phpfmt/pull/231

**Comment by ccirello** [comment]
Fixed by #231
